# the hyperparameters you don't add will use the default values from train(...) in ppo.py

CartPole-v0:
  epochs: 300
  gamma: 0.97
  gae_lambda: 0.9
  lr: 0.001
  num_steps: 256
  minibatch_size: 64
  ent_coef: 0.01
  clip_ratio: 0.2
  vf_coef: 0.5
  update_epochs: 3
  seed: 42

LunarLander-v2:
  epochs: 300
  gamma: 0.97
  gae_lambda: 0.9
  lr: 0.001
  num_steps: 256
  minibatch_size: 64
  ent_coef: 0.01
  clip_ratio: 0.2
  vf_coef: 0.5
  update_epochs: 3
  seed: 42

Reacher-v4:
  epochs: 300
  gamma: 0.97
  gae_lambda: 0.9
  lr: 0.001
  num_steps: 256
  minibatch_size: 64
  ent_coef: 0.01
  clip_ratio: 0.2
  vf_coef: 0.5
  update_epochs: 3
  seed: 42
