CartPole-v0:
  clip_ratio: 0.2
  ent_coef: 0.01
  epochs: 300
  gae_lambda: 0.9
  gamma: 0.97
  lr: 0.001
  minibatch_size: 64
  num_steps: 256
  seed: 42
  update_epochs: 3
  vf_coef: 0.5

LunarLander-v2:
  clip_ratio: 0.2
  ent_coef: 0.01
  epochs: 300
  gae_lambda: 0.9
  gamma: 0.97
  lr: 0.001
  minibatch_size: 64
  num_steps: 256
  seed: 42
  update_epochs: 3
  vf_coef: 0.5

Reacher-v4:
  clip_ratio: 0.3
  ent_coef: 0.0001
  epochs: 600
  gae_lambda: 0.91
  gamma: 0.985
  lr: 0.001
  minibatch_size: 256
  num_steps: 2048
  seed: 42
  update_epochs: 3
  vf_coef: 0.5
